// angularcrud/frontend/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-navbar',
  imports: [RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css',
})
export class NavbarComponent {}
<div class="container">
    <div class="header">
        <h1>My Users</h1>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <!-- <li><a routerLink="/prima-pagina" routerLinkActive="active" ariaCurrentWhenActive="page">Home</a></li>
                    <li><a routerLink="/myadmin" routerLinkActive="active" ariaCurrentWhenActive="page">Admin</a></li>
                  -->
                    <li class="nav-item">
                        <a class="nav-link" routerLink="/prima-pagina" routerLinkActive="active"
                            ariaCurrentWhenActive="page">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" [routerLink]="['/secret']" routerLinkActive="router-link-active">Admin</a>
                    </li>

                </ul>
            </div>
        </nav>
    </div>
</div>

// vuecrud/frontend/src/components/NavBar.vue
<template>
    <div class="container">
      <nav class="px-3 navbar navbar-expand navbar-dark bg-info">
        <router-link to="/" class="navbar-brand">CRUD Vue</router-link>
        <div class="navbar-nav mr-auto">
          <li class="nav-item">
            <router-link to="/users" class="nav-link">Home</router-link>
          </li>
          <li class="nav-item">
            <router-link to="/add" class="nav-link">Add User</router-link>
          </li>
          <li class="nav-item">
            <router-link to="/admin" class="nav-link">Admin</router-link>
          </li>
        </div>
      </nav>
    </div>
  </template>
  <script>
  export default {
    name: "nav-users",
    data() {
      return {};
    },
  };
  </script>
